name: pixelfield_flutter
description: "A new Flutter project using product collection, mock JSON, BLoC, shared_preferences, and go_router."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
 
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  go_router: ^7.0.0
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.1.1
  http: ^1.5.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: ^6.6.0

flutter_native_splash:
  image: "assets/images/logo4x.png"
  color: "#0B1519"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mock_data/products.json
